//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassesTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Classes : global::System.Configuration.ApplicationSettingsBase {
        
        private static Classes defaultInstance = ((Classes)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Classes())));
        
        public static Classes Default {
            get {
                return defaultInstance;
            }
        }
    }
}
